// import type { Metadata } from "next";

import { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Children {
  children: ReactNode;
}

export default function RootLayout({ children }: Children) {
  return (
    <html lang="en">
      <body className="text-gray-400 bg-zinc-950 dark:bg-white">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
