// import type { Metadata } from "next";

import { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./Navbar";
import DotPattern from "@/components/ui/dot-pattern";
import { cn } from "@/lib/utils";
import GridPattern from "@/components/ui/grid-pattern";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Children {
  children: ReactNode;
}

export default function RootLayout({ children }: Children) {
  return (
    <html lang="en">
      <body className="text-gray-400 bg-zinc-950 dark:bg-white">
        <Navbar />
        <main>
          {children}
          <GridPattern
            width={30}
            height={30}
            x={-1}
            y={-1}
            strokeDasharray={"4 2"}
            className={cn(
              "[mask-image:radial-gradient(300px_circle_at_center,white,transparent)]"
            )}
          />
        </main>
      </body>
    </html>
  );
}
